export const StringConstants = {
  LOGIN: "Login",
  EMAIL_USERNAME: "Email ID / Username",
  ENTER_EMAIL_USERNAME: "Enter Email ID / Username",
  PASSWORD: "Password",
  ENTER_PASSWORD: "Enter Password",
  FORGOT_PASSWORD: "Forget Password?",
  SIGNUP: "Signup",
  PROFILE: "Profile",
  COMPANY_NAME: "Company Name",
  R: "r",
  DARK_CONTENT: "dark-content",
  ENTER_COMPANY: "Enter Company Name",
  SIGN_UP: " Sign Up",
  DO_NOT_HAVE_ACCOUNT: "Don't have an account? ",
  DOCUMENT_TYPE_TEXT: " DOC, DOCx, PDF, RTF | Max: 2 MB ",
  I_AM_EXPERIENCED: "I'm Experienced",
  I_HAVE_WORK_EXPERIENCE: "I have work experience (excluding internships)",
  FRESHER: "I'm a Fresher",
  STUDENT_WORK_AFTER_GRADUATION:
    "I am a student/ Haven't worked after graduation",
  MOBILE_HINT: "Recruiters will call you on this number",
  PASSWORD_HINT: "Minimum 6 characters required",
  T_C: " Terms and Conditions",
  PRIVACY_POLICY: " Privacy Policy ",
  AND: " & ",
  EMAIL_TITLE_HINT: "We'll send you relevant jobs in your mail",
  EMAIL_PLACEHOLDER: "Tell us your Email ID",
  EMAIL_ID: "Email Id",
  FULL_NAME: "Full Name",
  FULL_NAME_PLACEHOLDER: "What is your name?",
  FIND_A_JOB: "Find a Job & Grow your career",
  PASSWORD_STRING: "Password",
  PASSWORD_PLACEHOLDER: "Create a password for your account",
  MOBILE_NUMBER: "Mobile Number",
  TC_TEXT: " By clicking Register, you agree to the",
  OF_NAUKARI: "of Naukari.com",
  ENTER_COMPANY_WEBSITE:"Enter Company Website",
  UPLOAD_RESUME: "Upload Resume",
  COMPANY_WEBSITE: "Company Website",
  REGISTER_NOW: "Register Now",
  RESUME: "Resume",
  WORK_STATUS: "Work Status",
  FIND_EMP: "Find a Employee",
  COMPANY: "Company",

  RESET_PASSWORD: "Reset Password",
  PASSWORD_DESCRIPTION:
    "Enter the email associated with your account and we'll send an email with instruction to reset your password.",
  SEND_PASSWORD: "Send Password",
  SKILLS: "Skills",
  EXAMPLE_MAIL: "example@gmail.com",
  ADDRESS: "Address",
  ADD_ADDRESS: "Add skills",
  APPLY_NOW: "Apply Now",
  CHANGE_PASSWORD: "Change Password",
  CHANGE_PASSWORD_DES:
    "To change password first enter your old password and than enter new password and click on Change Password button",
  OLD_PASSWORD: "Old Password",
  CHANGE_PASSWORD_PLACEHOLDER: "Enter Your Old Password",
  NEW_PASSWORD: "New Password",
  CHANGE_PASSWORD_NEW_PLACEHOLDER: "Enter Your New Password",
  JOB_SEEKER: "Job Seeker",
  RECRUITER: "Recruiter",
  SEARCH_JOB: "search Jobs",
  JOBS: "Jobs",
  SHOW: "Show",
  MALE: "Male",
  FEMALE: "Female",
  GENDER: "Gender",
  HIDE: "Hide",
  ADD_REMOVE: "Add or remove the companies you wish to hide your profile from",
  BLOCK_COMPANIES: "Blocked Companies",
  JOB_PREFERENCES: "Job Prefernces",
  JOB_PREFERENCES_DESC:
    "It will show job recommendations based on your Job Prefernces",
  T_C_DESC: "Control the visibility of your profile to recuiters & companies",
  T_C_PAGE: "TermAndCond",
  ACCOUNT: "Account",
  LOG_OUT: "Log Out",
  REGISTRATION_SUCCESSFUL: "registration successful",
  LOGIN_SUCCESS: "Login Success",
  SETTING: "Setting",
  REACT_NATIVE: "React Native",
  LOCATION_NOIDA: "Location: Noida",
  SALARY_LAKH: "Salary: 3L - 5L",
  EXP_FRESHER: "Experience: Fresher",
  EDIT_POST: "Edit Post",
  POST_JOBS: "Post Job",
  JOB_TITLE: "Job Title",
  JOB_PLACEHOLDER: "Enter Job Title",
  COMPANY_PLACEHOLDER: "Enter Company Name",
  LOCATION: "Location",
  SALARY: "Salary",
  EXPERIENCE: "Experience",
  CANCLE: "Cancel",
  COUNTRY_CODE: "+91",
  TERM_CON: "Term & Condition",
  LARGE: "large",
  CHOOSE: "Choose",
  CAMERA_OPTION: "Camera or Gallery",
  CAMERA: "Camera",
  GALLERY: "Gallery",
  HELLO_TEAM: "Hello Team",
  MIDDLE: "middle",
  SLIDE: "slide",
  SAVE: "Save",
};

export const ErrorConstants = {
  EMAIL: "Please Enter valid email",
  EMAIL_REQUIRED: "Email Address is required",
  PASSWORD_MUST: "Password must be in",
  CHARACTER: "characters",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_MATCHES: "Must contains upper,lower and special character",
  WRONG_EMAIL: "Wrong Formate Email",
  MOBILE_NO_REQUIRED: "Mobile No. is required",
  MOBILE_NO_MUST_BE: "Mobile No. Must be",
  CHARACTERS: "Characters",
  NAME_IS_REQUIRED: "Name is required",
  NAME_MUST_BE: "Name must be",
  MUST_BE_CHARACTER: "Must be characters",
};

export const RouteConstants = {
  LOGIN: "Login",
  SIGNUP: "Signup",
  FORGOT_PASSWORD: "ForgotPassword",
  CONFIRM_EMAIL: "ConfirmEmail",
  TERM_CONDITION: "TermAndCond",
  PRIVACY_AND_POLICY: "PrivacyAndPolicy",
  DRAWER_NAVIGATOR: "DrawerNavigator",
  HOME: "Home",
  PROFILE: "Profile",
  SETTING: "Setting",
  CHANGE_PASSWORD: "ChangePassword",
  JOB_SEEKER: "JobSeeker",
  RECRUITER_DASHBOARD: "RecuiterDashBoard",
  RECRUITER_JOB_POST: "recruiterJobPost",
};

export const ApiUrl = {
  BASEURL: "https://6a65-182-74-85-106.ngrok-free.app/api",
  CANDIDATE_LOGIN: "/login/",
  CHANGE_PASSWORD: "/change/password/",
  CANDIDATE_GET_PROFILE: "/candidate/profile/",
  CANDIDATE_SIGNUP: "/signup/",
  CANDIDATE_EDIT_PROFILE: "/candidate/edit/profile/",
  RECRUITER_JOB: "/recruiter/job/",
  REFRESH_TOKEN:'/refresh/token/',
  CANDIDATE_JOB: '/candidate/job/list/',
};

export const InputBoxConstants = {
  EMAIL: "email",
  PASSWORD: "password",
  COMPANY_NAME: "company_name",
  OLD_PASSWORD: "oldPassword",
  NEW_PASSWORD: "newPassword",
  FULL_NAME: "fullname",
  MOBILE_NUMBER: "mobile_number",
  COMPANY_WEBSITE: "company_website",
  SKILLS: "skills",
  ADDRESS: "address",
  MOBILENUMBER: "mobileNumber",
  COMPANY: "company",
  FULLNAME: "fullName",
  NONE: "none",
};

export const ToastConstants = {
  INVALID_SERVER: "Invalid Server",
  SUCCESSFULLY_LOGIN: "SuccessFullyLogin",
};

export const AlignmentConstants = {
  CENTER: "center",
  ABSOLUTE: "absolute",
  BOLD: "bold",
  ROW: "row",
  SPACE_BETWEEN: "space-between",
  FLEX_END: "flex-end",
  SPACE_EVENLY: "space-evenly",
  RELATIVE: "relative",
  ROW_REVERSE: "row-reverse",
};

export const RegexConstants = {
  PASSWORD: /^[a-zA-Z0-9!@#$%^&*]{6,16}$/,
  NAME: /^[a-zA-Z ]{2,40}$/,
  MOBILE_NUMBER: /^[789]\d{9}$/,
};

export const WebViewUrl = {
  PRIVACY_POLICY: "https://www.naukri.com/privacypolicy",
  TERM_CONDITION: "https://www.naukri.com/termsconditions",
};
