export const AppImages = {
  EXPERIENCED: require("../assets/icon/experience.png"),
  FRESHER: require("../assets/icon/fresher.png"),
  MENU: require("../assets/icon/menu.png"),
  SEARCH: require("../assets/icon/search.png"),
  FILLED_HEART: require("../assets/icon/filledHeart.png"),
  EMPTY_HEART: require("../assets/icon/emptyHeart.png"),
  JOB_POST: require("../assets/icon/jobPost.png"),
  BACK: require("../assets/icon/back.png"),
  USER: require("../assets/images/user.png"),
  EDIT_USER: require("../assets/images/edit.png"),
  SUCCESS_TOAST: require("../assets/icon/successToast.png"),
  ERROR_TOAST: require("../assets/icon/warningToast.png"),
  NEXT: require("../assets/icon/next.png"),
};
